# Generated by Django 4.0.6 on 2022-07-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('time', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[['Endbajarilad', 'Endbajarilad'], ['Bajarilyabt', 'Bajarilyabt']], max_length=50)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
